# Generated by Django 3.2.9 on 2021-12-06 14:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SwingDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('สีดำ', 'สีดำ'), ('สีขาว', 'สีขาว'), ('สีเทา', 'สีเทา'), ('สีลายไม้อ่อน', 'สีลายไม้อ่อน'), ('สีลายไม้เข้ม', 'สีลายไม้เข้ม')], default='สีขาว', max_length=20)),
                ('thick', models.CharField(choices=[('1.0 mm', '1.0 mm'), ('1.2 mm', '1.2 mm'), ('1.5 mm', '1.5 mm'), ('1.6 mm', '1.6 mm'), ('2.0 mm', '2.0 mm')], default='1.2 mm', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlidingDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('สีดำ', 'สีดำ'), ('สีขาว', 'สีขาว'), ('สีเทา', 'สีเทา'), ('สีลายไม้อ่อน', 'สีลายไม้อ่อน'), ('สีลายไม้เข้ม', 'สีลายไม้เข้ม')], default='สีขาว', max_length=20)),
                ('thick', models.CharField(choices=[('1.0 mm', '1.0 mm'), ('1.2 mm', '1.2 mm'), ('1.5 mm', '1.5 mm'), ('1.6 mm', '1.6 mm'), ('2.0 mm', '2.0 mm')], default='1.2 mm', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm_cost', models.FloatField()),
                ('kg_cost', models.FloatField()),
                ('labor_cost', models.IntegerField()),
                ('transport_cost', models.IntegerField()),
                ('tools_cost', models.IntegerField()),
                ('other_cost', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Glasscost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glassType', models.CharField(choices=[('กระจกเทมเปอร์', 'กระจกเทมเปอร์'), ('กระจกเขียวตัดแสง', 'กระจกเขียวตัดแสง'), ('กระจกใส', 'กระจกใส'), ('กระจกลามิเนต', 'กระจกลามิเนต'), ('กระจกชาดำ', 'กระจกชาดำ'), ('กระจกอินซูเลท', 'กระจกอินซูเลท'), ('กระจกฝ้า', 'กระจกฝ้า')], default='กระจกใส', max_length=20)),
                ('glassThick', models.CharField(choices=[('4.0 mm', '4 mm'), ('5.0 mm', '5 mm'), ('6.0 mm', '6 mm'), ('8.0 mm', '8 mm'), ('10.0 mm', '10 mm'), ('12.0mm', '12 mm')], default='6.0 mm', max_length=20)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoorFoldingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('สีดำ', 'สีดำ'), ('สีขาว', 'สีขาว'), ('สีเทา', 'สีเทา'), ('สีลายไม้อ่อน', 'สีลายไม้อ่อน'), ('สีลายไม้เข้ม', 'สีลายไม้เข้ม')], default='สีขาว', max_length=20)),
                ('thick', models.CharField(choices=[('1.0 mm', '1.0 mm'), ('1.2 mm', '1.2 mm'), ('1.5 mm', '1.5 mm'), ('1.6 mm', '1.6 mm'), ('2.0 mm', '2.0 mm')], default='1.2 mm', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
